variables: 
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: devops-acr-connection
    imageRepository: devops-course-repository
    containerRegistry: matheusdevopscourseregistry
    dockerfilePath: '$(Build.sourcesDirectory/Dockerfile)'
    tag: 'latest' #'$(Build.BuildId)'

    #Agent Vm image name
    vmImageName: 'ubuntu-latest'

steps:
  - task: AzureWebAppContainer@1 #Description that the task will execute
    inputs:
      azureSubscription: 'devops-appservice-resource-group' 
      appName: 'devops-course-webapp-test2'
      containers: $(containerRegistry)/$(imageRepository):$(tag)